Repository vmware/vic, pull requests merged in 2018-03, with the labels that each got.

#7430 Add appropriate secret to publish step
  .drone.yml
Labels: cla-not-required

#7432 Revert DRONE_HOSTNAME to DRONE_MACHINE
  tests/ci-env.sh
  tests/resources/VCH-Util.robot
Labels: cla-not-required

#7429 Fix group 6 delete tests
  .drone.local.yml
  tests/test-cases/Group6-VIC-Machine/6-03-Delete.robot
Labels: cla-not-required

#7424 Build non-stripped binaries when env VIC_DEBUG_BUILD is set
  Makefile
  infra/scripts/version-debug-linker-flags.sh
Labels: cla-not-required

#7435 Add scripts to provide dlv support in the VCH
  infra/vch-dlv/README.md
  infra/vch-dlv/dlv-ctl.sh
  infra/vch-dlv/dlv-setup.sh
Labels: cla-not-required

#7436 Added no strict host checking
  infra/vch-dlv/dlv-ctl.sh
  infra/vch-dlv/dlv-setup.sh
Labels: cla-not-required

#7443 Renamed folder, plus progress messages, plus fix iptables
  infra/dlv/README.md
  infra/dlv/dlv-ctl.sh
  infra/dlv/dlv-setup.sh
Labels: cla-not-required

#7420 "Handle event resubscription to PL when it panics" or something that pertains to the fix.
  lib/apiservers/engine/backends/eventmonitor.go
Labels: cla-not-required

#7446 Provide more time for slower VC operations
  tests/test-cases/Group8-vSphere-Integration/8-01-GuestTools.robot
Labels: cla-not-required

#7449 Stop blowing away our vm-network
  tests/test-cases/Group6-VIC-Machine/6-07-Create-Network.robot
Labels: cla-not-required

#7447 Fix container network name assumptions to work with VC setup
  tests/test-cases/Group6-VIC-Machine/6-07-Create-Network.robot
  tests/test-cases/Group6-VIC-Machine/6-16-Config.robot
Labels: cla-not-required

#7413 Create a new, unique bridge network on a random VLAN for VC
  .drone.yml
  tests/resources/VCH-Util.robot
Labels: cla-not-required

#7453 Fixed Copyright and some spelling error
  infra/dlv/README.md
  infra/dlv/dlv-ctl.sh
  infra/dlv/dlv-setup.sh
Labels: cla-not-required

#7433 Initial rudimentary implementation of vm placement library
  pkg/vsphere/compute/placement/placement.go
  pkg/vsphere/compute/placement/random.go
  pkg/vsphere/compute/placement/random_test.go
  pkg/vsphere/compute/placement/ranked.go
  pkg/vsphere/compute/placement/ranked_test.go
  pkg/vsphere/performance/host_metrics.go
  pkg/vsphere/performance/host_metrics_test.go
  pkg/vsphere/performance/metrics_provider.go
Labels: cla-not-required

#7445 Tmp copy for mutating array iteration
  lib/portlayer/network/context.go
Labels: cla-not-required

#7455 Reduce number of iterations
  tests/test-cases/Group1-Docker-Commands/1-40-Docker-Restart.robot
Labels: cla-not-required

#7457 [skip ci]Add datacenter to govc env for longevity test
  tests/longevity-tests/Dockerfile.6.5
Labels: cla-not-required

#7460 Various network fixes to ensure each test is on the proper network in VC
  CONTRIBUTING.md
  tests/resources/VCH-Util.robot
  tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot
  tests/test-cases/Group10-VCH-Restart/10-01-VCH-Restart.robot
  tests/test-cases/Group6-VIC-Machine/6-07-Create-Network.robot
Labels: cla-not-required

#7472 Comment out test until known issue is resolved
  tests/test-cases/Group1-Docker-Commands/1-07-Docker-Stop.robot
Labels: cla-not-required

#6787 Add better handling of exec operations during poweroff
  cmd/tether/attach.go
  lib/apiservers/engine/backends/container.go
  lib/apiservers/engine/backends/container_proxy.go
  lib/apiservers/engine/backends/container_test.go
  lib/apiservers/engine/backends/errors.go
  lib/apiservers/portlayer/restapi/handlers/containers_handlers.go
  lib/apiservers/portlayer/restapi/handlers/task_handlers.go
  lib/apiservers/portlayer/swagger.json
  lib/portlayer/exec/base.go
  lib/portlayer/exec/container.go
  lib/portlayer/task/common.go
  lib/portlayer/task/inspect.go
  lib/portlayer/task/wait.go
  lib/tether/config.go
  lib/tether/tether.go
  tests/resources/Docker-Util.robot
  tests/test-cases/Group1-Docker-Commands/1-38-Docker-Exec.md
  tests/test-cases/Group1-Docker-Commands/1-38-Docker-Exec.robot
Labels: cla-not-required

#7324 Debug and dev workflow improvements
  .gitignore
  infra/scripts/README.md
  infra/scripts/bash-helpers.sh
  infra/scripts/sample-helper.profiles
  isos/appliance/nat-setup
Labels: area/infra, cla-not-required

#7323 Plan testing for upgrade and configure APIs
  doc/test_plans/vic-machine-service/upgrade-rollback-configure.md
  tests/test-cases/Group23-VIC-Machine-Service/23-07-VCH-Reconfigure.md
  tests/test-cases/Group23-VIC-Machine-Service/23-09-VCH-Upgrade.md
Labels: cla-not-required

#7262 Tar bug cp online case
  Makefile
  cmd/archive/unpack.go
  cmd/tether/attach.go
  cmd/tether/attach_test.go
  cmd/tether/haveged_linux.go
  cmd/tether/tether_test.go
  cmd/vic-init/tether_test.go
  isos/bootstrap.sh
  isos/bootstrap/bootstrap
  lib/archive/unpack_unix.go
  lib/archive/unpack_unix_test.go
  lib/archive/unpack_windows.go
  lib/portlayer/storage/data_sink.go
  lib/tether/interfaces.go
  lib/tether/tether.go
  lib/tether/tether_test.go
  lib/tether/toolbox.go
  pkg/logmgr/logmgr.go
  pkg/logmgr/logmgr_test.go
  tests/test-cases/Group1-Docker-Commands/1-43-Docker-CP-Offline.robot
  tests/test-cases/Group1-Docker-Commands/1-44-Docker-CP-Online.robot
Labels: cla-not-required

#7381 [skip ci] Add documentation for make push to README.md
  README.md
Labels: cla-not-required

#7465 Verify license present in nightly env
  lib/install/validate/config.go
  tests/manual-test-cases/Group5-Functional-Tests/5-3-Enhanced-Linked-Mode.robot
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7478 Wait for VCH to properly register the die event
  tests/test-cases/Group1-Docker-Commands/1-25-Docker-Port-Map.robot
Labels: cla-not-required

#7479 Don't fail if you can't delete other build datastore items
  tests/resources/VCH-Util.robot
Labels: cla-not-required

#7440 Basic vic-machine ROBO support
  lib/install/management/appliance.go
  lib/install/management/create.go
  lib/install/management/finder.go
  lib/install/management/resource_pool.go
  lib/install/validate/compute.go
  lib/install/validate/config.go
  lib/install/validate/validator.go
  lib/install/validate/validator_test_sim_util.go
  pkg/vsphere/compute/cluster.go
  pkg/vsphere/session/session.go
  tests/test-cases/Group6-VIC-Machine/6-11-Debug.robot
Labels: cla-not-required

#7480 Cleanup the network tests and make sure any network that expects to be public is on correct VLAN
  .drone.yml
  tests/test-cases/Group6-VIC-Machine/6-07-Create-Network.robot
Labels: cla-not-required

#7469 Ensure non-overlapping unique bridges in a shared environment
  tests/resources/VCH-Util.robot
Labels: cla-not-required

#7467 Make sure to specify the token so we don't hit the API limit
  .drone.yml
  tests/unit-test-check.sh
Labels: cla-not-required

#7474 Explicitly clone PR to avoid merge master
  .drone.yml
Labels: cla-not-required

#7476 Use random placement library for VCH creation
  lib/install/management/create.go
  lib/install/management/create_test.go
  tests/manual-test-cases/Group19-ROBO/19-3-ROBO-VM-Placement.md
Labels: cla-not-required

#7409 Refactor VM delete process: re-enable destroy on VM, add retry pattern to concurrent access error
  lib/install/management/appliance.go
  lib/portlayer/exec/container.go
  pkg/vsphere/tasks/waiter.go
  pkg/vsphere/tasks/waiter_test.go
  pkg/vsphere/vm/vm.go
  pkg/vsphere/vm/vm_test.go
  tests/concurrent/concurrent.go
Labels: cla-not-required

#7468 Don't remove the unique bridge when running locally
  tests/resources/VCH-Util.robot
  tests/resources/Vsphere-Util.robot
  tests/test-cases/Group10-VCH-Restart/10-01-VCH-Restart.robot
  tests/test-cases/Group12-VCH-BC/12-01-Delete.robot
  tests/test-cases/Group6-VIC-Machine/6-02-Default.robot
  tests/test-cases/Group6-VIC-Machine/6-03-Delete.robot
  tests/test-cases/Group6-VIC-Machine/6-04-Create-Basic.robot
  tests/test-cases/Group6-VIC-Machine/6-07-Create-Network.robot
  tests/test-cases/Group6-VIC-Machine/6-09-Inspect.robot
  tests/test-cases/Group6-VIC-Machine/6-16-Config.robot
Labels: cla-not-required

#7488 Added DLV support for vic-machine + refactor
  Makefile
  infra/dlv/README.md
  infra/dlv/dlv-ctl.sh
  infra/dlv/dlv-setup.sh
  infra/scripts/version-debug-linker-flags.sh
  infra/scripts/version-linker-flags.sh
  pkg/log/log.go
  pkg/trace/trace.go
Labels: cla-not-required

#7489 Remove license check for vCenter in nightly
  tests/manual-test-cases/Group5-Functional-Tests/5-3-Enhanced-Linked-Mode.robot
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7490 [skip ci] fixing skip ci doc
  CONTRIBUTING.md
Labels: cla-not-required

#7454 Vch inventory folder support
  lib/install/management/appliance.go
  lib/install/management/create.go
  lib/install/management/delete.go
  lib/install/management/delete_test.go
  lib/install/management/resource_pool.go
Labels: cla-not-required

#7486 Add support for 6.7 interop in our nightlies
  tests/manual-test-cases/Group5-Functional-Tests/5-5-Heterogeneous-ESXi.robot
  tests/nightly/jenkins-nightly-run.sh
  tests/nightly/upload-logs.sh
Labels: cla-not-required

#7494 Fix spelling issues in robo feature branch
  lib/install/management/create.go
Labels: cla-not-required

#7450 Issue gratuitous ARP request on network update
  lib/tether/ops_linux.go
  vendor/github.com/mdlayher/arp/LICENSE.md
  vendor/github.com/mdlayher/arp/client.go
  vendor/github.com/mdlayher/arp/cmd/arpc/main.go
  vendor/github.com/mdlayher/arp/cmd/proxyarpd/main.go
  vendor/github.com/mdlayher/arp/doc.go
  vendor/github.com/mdlayher/arp/fuzz.go
  vendor/github.com/mdlayher/arp/packet.go
  vendor/github.com/mdlayher/arp/string.go
  vendor/github.com/mdlayher/ethernet/LICENSE.md
  vendor/github.com/mdlayher/ethernet/cmd/etherecho/main.go
  vendor/github.com/mdlayher/ethernet/ethernet.go
  vendor/github.com/mdlayher/ethernet/fuzz.go
  vendor/github.com/mdlayher/ethernet/string.go
  vendor/github.com/mdlayher/ethernet/vlan.go
  vendor/github.com/mdlayher/raw/LICENSE.md
  vendor/github.com/mdlayher/raw/raw.go
  vendor/github.com/mdlayher/raw/raw_bsd.go
  vendor/github.com/mdlayher/raw/raw_linux.go
  vendor/github.com/mdlayher/raw/raw_others.go
  vendor/github.com/mdlayher/raw/timeval.go
  vendor/github.com/mdlayher/raw/timeval32.go
  vendor/github.com/mdlayher/raw/timeval_darwin.go
  vendor/golang.org/x/net/bpf/LICENSE
  vendor/golang.org/x/net/bpf/asm.go
  vendor/golang.org/x/net/bpf/constants.go
  vendor/golang.org/x/net/bpf/doc.go
  vendor/golang.org/x/net/bpf/instructions.go
  vendor/golang.org/x/net/bpf/setter.go
  vendor/golang.org/x/net/bpf/vm.go
  vendor/golang.org/x/net/bpf/vm_instructions.go
  vendor/manifest
Labels: cla-not-required

#7444 Make NFS mount target clean path
  lib/tether/ops_linux.go
Labels: area/storage, cla-not-required, component/tether

#7456 Indicate what specific build we are waiting on
  tests/wait_until_previous_builds_complete.sh
Labels: cla-not-required

#7496 [skip ci]Only specify an old DVS version for the test that needs it - hetero
  tests/manual-test-cases/Group5-Functional-Tests/5-5-Heterogeneous-ESXi.robot
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7502 Pull the correct image for the bundle step
  .drone.yml
Labels: cla-not-required

#7503 Upgrade govc to fix panic and switch to json parsing of vlan
  .drone.local.yml
  .drone.yml
  infra/integration-image/Dockerfile
  infra/scripts/local-ci.sh
  tests/local-integration-test.sh
  tests/longevity-tests/Dockerfile.foundation
  tests/resources/Vsphere-Util.robot
Labels: cla-not-required

#7508 Enable full CI runs for feature/robo merges
  tests/integration-test.sh
Labels: cla-not-required

#7511 Run UI step on failure so that we can properly bundle
  .drone.yml
Labels: cla-not-required

#7501 Define test plan for existing VCH Management APIs
  doc/test_plans/vic-machine-service/create-list-inspect-delete.md
  tests/test-cases/Group23-VIC-Machine-Service/23-02-VCH-List.md
  tests/test-cases/Group23-VIC-Machine-Service/23-03-VCH-Create.md
  tests/test-cases/Group23-VIC-Machine-Service/23-04-VCH-Inspect.md
  tests/test-cases/Group23-VIC-Machine-Service/23-08-VCH-Delete.md
Labels: cla-not-required

#7441 Delete datastore files iteratively for all datastore types
  lib/install/management/store_files.go
Labels: cla-not-required

#7525 Fixed 2 persona crashes, updated tether, switched back to VK vic provider
  cmd/kubelet-starter/main.go
  lib/apiservers/engine/backends/backends.go
  lib/apiservers/engine/backends/container.go
  lib/apiservers/engine/network/utils.go
  lib/apiservers/engine/proxy/container_proxy.go
  lib/tether/tether_linux.go
Labels: cla-not-required

#7524 Fix folder deletion function
  lib/install/management/delete.go
  tests/test-cases/Group6-VIC-Machine/6-02-Default.robot
Labels: cla-not-required

#7458 Use a child context for image upload
  lib/install/management/create.go
Labels: cla-not-required

#7530 Improve logging for nightly debugging
  cmd/vic-machine/create/create.go
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7509 Remove direct transition to Starting pseudo state
  lib/portlayer/exec/container.go
  tests/test-cases/Group1-Docker-Commands/1-05-Docker-Start.robot
Labels: cla-not-required

#7506 Add pass rate publication step back to pipeline
  .drone.yml
Labels: cla-not-required

#6980 [skip ci] Make it a fatal error if vic machine fails to cleanup a VCH
  tests/resources/VCH-Util.robot
Labels: cla-not-required

#7551 [skip ci] Shorten lease time to 4hrs
  tests/manual-test-cases/Group5-Functional-Tests/5-3-Enhanced-Linked-Mode.robot
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7554 [skip ci] Double the default memory of our default testbed
  tests/resources/nimbus-testbeds/vic-simple-cluster.rb
Labels: cla-not-required

#7543 Update test for cleaned NFS share path
  tests/manual-test-cases/Group5-Functional-Tests/5-22-NFS-Volume.robot
Labels: cla-not-required

#7545 vic-machine create validation allows disabled DRS
  lib/install/validate/config.go
  lib/install/validate/config_to_data.go
  lib/install/validate/validator.go
  lib/install/validate/validator_test_sim_util.go
Labels: feature/robo

#7510 Fix TLS detection and add inspect config subcommand
  infra/scripts/README.md
  infra/scripts/bash-helpers.sh
Labels: cla-not-required

#7570 Make changes to allow pod vm work for demo 2b
  cmd/tether/ops.go
  lib/apiservers/engine/backends/eventmonitor.go
  lib/apiservers/engine/errors/errors.go
  lib/tether/tether_linux.go
Labels: cla-not-required

#7330 Update ROBO SKU test to use vSAN testbed
  tests/manual-test-cases/Group19-ROBO/19-1-ROBO-SKU.md
  tests/manual-test-cases/Group19-ROBO/19-1-ROBO-SKU.robot
  tests/resources/Nimbus-Util.robot
  tests/resources/nimbus-testbeds/vic-robo.rb
Labels: cla-not-required, feature/robo

#7062 Simplify vch log API handler
  lib/apiservers/service/restapi/handlers/vch_log_get.go
  pkg/vsphere/datastore/datastore.go
Labels: cla-not-required

#7483 Add ability to skip check membership on CI
  .drone.yml
  CONTRIBUTING.md
Labels: cla-not-required

#7527 Move drone clone step out of pipeline
  .drone.yml
Labels: cla-not-required

#7482 Fix drone cli link
  CONTRIBUTING.md
Labels: cla-not-required

#7535 Vic machine configure tlsverify
  cmd/vic-machine/configure/configure.go
  tests/test-cases/Group6-VIC-Machine/6-17-Configure-TLS.robot
Labels: cla-not-required

#7555 Improve nightly logging
  tests/manual-test-cases/Group21-Registries/21-1-Whitelist.robot
  tests/manual-test-cases/Group23-Future-Tests/23-2-Future-ISO-Install.robot
  tests/manual-test-cases/Group5-Functional-Tests/5-22-NFS-Volume.robot
  tests/manual-test-cases/Group5-Functional-Tests/5-4-High-Availability.robot
  tests/manual-test-cases/Group5-Functional-Tests/5-5-Heterogeneous-ESXi.robot
  tests/manual-test-cases/Group5-Functional-Tests/5-6-2-VSAN-Complex.robot
  tests/manual-test-cases/Group5-Functional-Tests/5-7-NSX.robot
  tests/resources/Nimbus-Util.robot
  tests/resources/VCH-Util.robot
  tests/resources/nimbus-testbeds/vic-vsan.rb
Labels: cla-not-required

#7566 skip deleting -sesparse.vmdk file in vic-machine delete
  lib/install/management/store_files.go
Labels: cla-not-required

#7546 [skip ci]Update 6.7 nightly to golden build 2
  tests/nightly/jenkins-nightly-run.sh
Labels: cla-not-required

#7575 Comment out part of test with known issue
  tests/test-cases/Group11-Upgrade/11-01-Upgrade.robot
Labels: cla-not-required

#7572 Re-organize ROBO testing layout
  tests/manual-test-cases/Group19-DRS-Disabled/19-1-DRS-Disabled-Vcenter-Connectivity.md
  tests/manual-test-cases/Group19-DRS-Disabled/19-2-DRS-Disabled-Container-Limit.md
  tests/manual-test-cases/Group19-DRS-Disabled/19-3-DRS-Disabled-Placement.md
  tests/manual-test-cases/Group19-DRS-Disabled/19-4-DRS-Disabled-License-Features.md
  tests/manual-test-cases/Group19-DRS-Disabled/TestCases.md
  tests/manual-test-cases/Group19-ROBO/19-1-ROBO-SKU.md
  tests/manual-test-cases/Group19-ROBO/TestCases.md
  tests/resources/ROBO-Util.robot
  tests/resources/Util.robot
Labels: cla-not-required, feature/robo

#7533 Update VCH inspect API to output TLS friendly docker host and admin portal address
  lib/apiservers/service/restapi/handlers/common.go
  lib/apiservers/service/restapi/handlers/vch_get.go
  lib/apiservers/service/restapi/handlers/vch_list_get.go
  lib/install/management/inspect.go
  tests/test-cases/Group6-VIC-Machine/6-09-Inspect.robot
Labels: cla-not-required

#7573 vic-machine upgrade ignores version check with force flag
  cmd/vic-machine/upgrade/upgrade.go
  tests/test-cases/Group6-VIC-Machine/6-11-Debug.robot
Labels: cla-not-required, feature/robo

#7577 Do not retrieve port for containers not found in cache.
  lib/apiservers/engine/backends/container.go
  lib/apiservers/engine/backends/container_test.go
  lib/apiservers/engine/network/utils.go
Labels: cla-not-required

#7589 add nil check for DRSEnabled for the cvm deletion path
  lib/install/management/delete.go
Labels: cla-not-required, feature/robo

#7581 Initial codecov configuration file
  .codecov.yml
  .drone.yml
Labels: cla-not-required

#7578 Add to vic-machine unit tests
  cmd/vic-machine/create/create_test.go
  cmd/vic-machine/delete/delete_test.go
Labels: cla-not-required

#7531 Enable host recommendation in vm power-on
  lib/install/management/configure.go
  lib/install/management/create.go
  lib/install/management/create_test.go
  lib/portlayer/exec/base.go
  lib/portlayer/exec/container_cache.go
  pkg/retry/retry.go
  pkg/vsphere/compute/placement/placement.go
  pkg/vsphere/compute/placement/random_test.go
  pkg/vsphere/compute/placement/ranked.go
  pkg/vsphere/compute/placement/ranked_test.go
  pkg/vsphere/performance/vm_subscription.go
  pkg/vsphere/vm/vm.go
  pkg/vsphere/vm/vm_test.go
  tests/manual-test-cases/Group19-DRS-Disabled/19-3-DRS-Disabled-Placement.md
  tests/manual-test-cases/Group19-DRS-Disabled/19-3-DRS-Disabled-Placement.robot
Labels: cla-not-required, feature/robo

#7553 Remove Wait in nightly test, rely on retry instead [skip ci]
  tests/manual-test-cases/Group5-Functional-Tests/5-5-Heterogeneous-ESXi.robot
Labels: cla-not-required

#7593 Install codecov and call it directly from unit tests
  .drone.local.yml
  .drone.yml
  infra/integration-image/Dockerfile
  infra/scripts/local-ci.sh
  tests/local-integration-test.sh
  tests/longevity-tests/Dockerfile.foundation
  tests/unit-test-check.sh
Labels: cla-not-required

#7505 Don't create a unique bridge in environments where the bridge is already defined
  .drone.yml
  tests/resources/VCH-Util.robot
  tests/test-cases/Group1-Docker-Commands/1-02-Docker-Pull.robot
  tests/test-cases/Group6-VIC-Machine/6-02-Default.robot
  tests/test-cases/Group6-VIC-Machine/6-03-Delete.robot
  tests/test-cases/Group6-VIC-Machine/6-04-Create-Basic.robot
  tests/test-cases/Group6-VIC-Machine/6-07-Create-Network.robot
Labels: cla-not-required

#7591 Remove superfluous type declaration [skip ci]
  lib/portlayer/exec/commit.go
  lib/portlayer/exec/exec.go
Labels: cla-not-required

#7594 Use runc to run containers in the pod vm
  isos/appliance-virtual-kubelet.sh
  isos/bootstrap.sh
  isos/bootstrap/bootstrap
  lib/tether/tether.go
  lib/tether/tether_linux.go
  vendor/github.com/opencontainers/runtime-spec/LICENSE
  vendor/github.com/opencontainers/runtime-spec/schema/validate.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/manifest
Labels: cla-not-required

#7574 vic-machine will not include VCH memory with snapshot
  lib/install/management/configure.go
  tests/test-cases/Group11-Upgrade/11-01-Upgrade.robot
Labels: feature/robo

#7584 Fix check membership step
  .drone.yml
Labels: cla-not-required

#7603 Pin gsutil version
  .drone.local.yml
  .drone.yml
  infra/integration-image/Dockerfile
  infra/scripts/local-ci.sh
  tests/local-integration-test.sh
  tests/longevity-tests/Dockerfile.foundation
Labels: cla-not-required

#7389 make push uses pki identity file
  infra/scripts/bash-helpers.sh
  infra/scripts/replace-running-components.sh
Labels: cla-not-required

#7587 Grant ops-user minimum privileges on entities
  cmd/vic-machine/common/ops_credentials.go
  lib/install/management/appliance.go
  lib/install/management/configure.go
  lib/install/management/create.go
  lib/install/management/delete.go
  lib/install/opsuser/opsuser.go
  lib/install/opsuser/opsuser_conf.go
  lib/install/opsuser/opsuser_test.go
  lib/install/validate/validator_test.go
  lib/install/validate/validator_test_sim_util.go
  pkg/vsphere/rbac/rbac.go
  pkg/vsphere/rbac/rbac_test.go
  tests/manual-test-cases/Group5-Functional-Tests/5-25-OPS-User-Grant.md
  tests/manual-test-cases/Group5-Functional-Tests/5-25-OPS-User-Grant.robot
Labels: cla-not-required, feature/robo

#7611 Some post-demo cleanup
  lib/apiservers/engine/backends/container.go
  lib/tether/tether.go
Labels: cla-not-required

#7579 Update nightly logging
  tests/manual-test-cases/Group5-Functional-Tests/5-7-NSX.robot
  tests/resources/Docker-Util.robot
  tests/resources/VCH-Util.robot
Labels: cla-not-required

#7616 Update nightly to latest vSphere builds
  tests/nightly/jenkins-nightly-run.sh
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7604 Implement module level coverage and start our range at current levels
  .codecov.yml
Labels: cla-not-required

#7615 Added more logs and retry operation for VM config change.
  pkg/vsphere/vm/vm.go
Labels: cla-not-required
