Repository vmware/vic, pull requests merged in 2018-05, with the labels that each got.

#7864 Allow for two different ping error messages
  tests/test-cases/Group1-Docker-Commands/1-24-Docker-Link.robot
Labels: cla-not-required

#7863 nightly: Disable 5-25-OPS-User-Grant upgrade test
  tests/manual-test-cases/Group5-Functional-Tests/5-25-OPS-User-Grant.robot
Labels: cla-not-required

#7862 Address spreading use of secret tag in our curl commands
  VCH-0-1212/VCH-0-1212.env
  tests/manual-test-cases/Group5-Functional-Tests/5-28-VICAdmin-Isolated.robot
  tests/resources/VCH-Util.robot
  tests/test-cases/Group9-VIC-Admin/9-01-VICAdmin-ShowHTML.robot
Labels: cla-not-required

#7873 Remove errant file that accidentally got merged
  VCH-0-1212/VCH-0-1212.env
Labels: cla-not-required

#7853 [skip ci] Nimbus testbed for nfs volume nightly test
  tests/manual-test-cases/Group5-Functional-Tests/5-22-NFS-Volume.robot
  tests/resources/Nimbus-Util.robot
  tests/resources/nimbus-testbeds/vic-nfs.rb
Labels: cla-not-required

#7871 validator: Remove ParseURL method
  lib/install/validate/validator.go
  lib/install/validate/validator_test.go
Labels: cla-not-required

#7702 Tweak codecov ignore paths and only report status on patch
  .codecov.yml
Labels: cla-not-required

#7883 Update the nightlies builds
  tests/nightly/jenkins-nightly-run.sh
Labels: cla-not-required

#7876 [skip ci] Configure ROBO nightlies with Group19-DRS-Disabled
  tests/drs-disabled/jenkins-drs-disabled-run.sh
  tests/drs-disabled/upload-logs.sh
  tests/manual-test-cases/Group19-DRS-Disabled/19-3-DRS-Disabled-Placement.robot
Labels: cla-not-required

#7884 Add timeouts in case of hung operations
  tests/manual-test-cases/Group5-Functional-Tests/5-25-OPS-User-Grant.robot
  tests/resources/Docker-Util.robot
Labels: cla-not-required

#7870 validator: Rename CreateFromVCHConfig method
  lib/install/validate/validator.go
  lib/install/validate/validator_test.go
  lib/vicadmin/validate.go
Labels: cla-not-required

#7772 [skip ci] Update vagrant drone version
  infra/machines/devbox/provision-drone.sh
Labels: cla-not-required

#7889 [skip ci] Fix tar extraction path in DRS-disabled nightlies
  tests/drs-disabled/jenkins-drs-disabled-run.sh
Labels: cla-not-required

#7866 updating to v1.4.0 license
  LICENSE
  doc/bundle/NOTICE
  open_source_license
Labels: cla-not-required

#7897 updating to v1.4.0 license (#7866) - cherrypick
  LICENSE
  doc/bundle/NOTICE
  open_source_license
Labels: cla-not-required

#7881 [skip ci] Add test for no-DRS VCH create with RP options
  tests/manual-test-cases/Group19-DRS-Disabled/19-4-DRS-Disabled-License-Features.md
  tests/manual-test-cases/Group19-DRS-Disabled/19-4-DRS-Disabled-License-Features.robot
Labels: cla-not-required

#7902 VCH install timeout set to 30m for 5-21-Datastore-Path
  tests/manual-test-cases/Group5-Functional-Tests/5-21-Datastore-Path.robot
Labels: cla-not-required

#7290 Add basic integration tests for VCH inspect API
  tests/resources/Group23-VIC-Machine-Service-Util.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-04-VCH-Inspect.robot
Labels: cla-not-required

#7894 installer: deduplicate upgrade status code
  cmd/vic-machine/inspect/inspect.go
  cmd/vic-machine/list/list.go
  lib/apiservers/service/restapi/handlers/common.go
  lib/install/interaction/upgrade_status.go
Labels: cla-not-required

#7905 Add project back into codecov results
  .codecov.yml
Labels: cla-not-required

#7906 Add NFS datastore keyword back
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7887 session: Note operations which omit UserAgent
  cmd/vic-ui/ui/ui.go
  lib/apiservers/engine/backends/backends.go
  lib/install/plugin/register.go
  pkg/vsphere/session/session.go
Labels: cla-not-required

#7852 [skip ci] Publish vic-machine-server with git tags
  .drone.yml
Labels: cla-not-required

#7909 [skip ci]Select correct datastore for the test
  tests/manual-test-cases/Group5-Functional-Tests/5-11-Multiple-Cluster.robot
  tests/resources/Nimbus-Util.robot
Labels: cla-not-required

#7899 datastore: clean up test utility code
  pkg/vsphere/datastore/datastore_test.go
  pkg/vsphere/datastore/datastore_util.go
Labels: cla-not-required

#7918 Create a new testbed that includes a static IP address worker
  tests/resources/Nimbus-Util.robot
  tests/resources/nimbus-testbeds/vic-simple-cluster-with-static.rb
Labels: cla-not-required

#7910 inspect: Use lower case naming for arguments
  lib/install/management/inspect.go
Labels: cla-not-required

#7911 validator: Make SetDataFromVM a validator method
  cmd/vic-machine/configure/configure.go
  cmd/vic-machine/inspect/inspect.go
  lib/apiservers/service/restapi/handlers/common.go
  lib/apiservers/service/restapi/handlers/vch_delete.go
  lib/apiservers/service/restapi/handlers/vch_get.go
  lib/apiservers/service/restapi/handlers/vch_log_get.go
  lib/install/validate/config_to_data.go
Labels: cla-not-required

#7914 Extract en/decode packages for vic-machine API
  lib/apiservers/service/restapi/handlers/decode/certificates.go
  lib/apiservers/service/restapi/handlers/decode/decode.go
  lib/apiservers/service/restapi/handlers/decode/delete.go
  lib/apiservers/service/restapi/handlers/decode/networking.go
  lib/apiservers/service/restapi/handlers/decode/references.go
  lib/apiservers/service/restapi/handlers/decode/resources.go
  lib/apiservers/service/restapi/handlers/encode/certificates.go
  lib/apiservers/service/restapi/handlers/encode/encode.go
  lib/apiservers/service/restapi/handlers/encode/networking.go
  lib/apiservers/service/restapi/handlers/encode/references.go
  lib/apiservers/service/restapi/handlers/encode/resources.go
  lib/apiservers/service/restapi/handlers/vch_cert_get.go
  lib/apiservers/service/restapi/handlers/vch_create.go
  lib/apiservers/service/restapi/handlers/vch_delete.go
  lib/apiservers/service/restapi/handlers/vch_get.go
Labels: cla-not-required

#7915 Extract logging package for vic-machine API
  lib/apiservers/service/restapi/handlers/logging/logging.go
  lib/apiservers/service/restapi/handlers/vch_create.go
Labels: cla-not-required

#7924 Correct bad merge resolution in 517f3ac505
  lib/apiservers/service/restapi/handlers/vch_log_get.go
Labels: cla-not-required

#7917 [skip ci] Update vagrant box to ubuntu 18.04
  Vagrantfile
Labels: cla-not-required

#7892 Enable CI to run tests as ops user [specific ci=Group11-Upgrade] [ops user]
  .drone.yml
  tests/integration-test.sh
  tests/resources/VCH-Util.robot
  tests/test-cases/Group1-Docker-Commands/1-08-Docker-Logs.md
  tests/test-cases/Group1-Docker-Commands/1-08-Docker-Logs.robot
  tests/test-cases/Group11-Upgrade/11-01-Upgrade.md
  tests/test-cases/Group11-Upgrade/11-01-Upgrade.robot
  tests/test-cases/Group11-Upgrade/11-02-Upgrade-Exec.robot
  tests/test-cases/Group11-Upgrade/11-02-Upgrade-InsecureRegistry.md
  tests/test-cases/Group11-Upgrade/11-02-Upgrade-InsecureRegistry.robot
  tests/test-cases/Group11-Upgrade/11-03-Upgrade-UpdateInProgress.md
  tests/test-cases/Group11-Upgrade/11-03-Upgrade-UpdateInProgress.robot
  tests/test-cases/Group11-Upgrade/11-04-Configure.md
  tests/test-cases/Group11-Upgrade/11-04-Configure.robot
  tests/test-cases/Group11-Upgrade/11-05-Configure.md
  tests/test-cases/Group11-Upgrade/TestCases.md
  tests/test-cases/Group23-VIC-Machine-Service/23-06-VCH-Certificate.robot
Labels: cla-not-required

#7922 Simplify error formatting logic in vic-machine API
  lib/apiservers/service/restapi/handlers/common.go
  lib/apiservers/service/restapi/handlers/vch_cert_get.go
  lib/apiservers/service/restapi/handlers/vch_create.go
  lib/apiservers/service/restapi/handlers/vch_delete.go
  lib/apiservers/service/restapi/handlers/vch_get.go
  lib/apiservers/service/restapi/handlers/vch_log_get.go
  tests/test-cases/Group23-VIC-Machine-Service/23-03-VCH-Create.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-06-VCH-Certificate.robot
Labels: cla-not-required, team/lifecycle

#7946 Unset opsuser args in normal tests [specific ci=25-02-Reconfigure]
  tests/test-cases/Group23-VIC-Machine-Service/23-06-VCH-Certificate.robot
  tests/test-cases/Group25-Host-Affinity/25-02-Reconfigure.md
  tests/test-cases/Group25-Host-Affinity/25-02-Reconfigure.robot
Labels: cla-not-required

#7947 Add opsuser var to nightly script [skip ci]
  tests/nightly/jenkins-nightly-run.sh
Labels: cla-not-required

#7451 Support for dlv remote debugging
  README.md
  infra/dlv/README.md
  infra/dlv/dlv-ctl.sh
  infra/dlv/dlv-setup.sh
  infra/integration-image/scripts/README.md
  infra/scripts/version-linker-flags.sh
  isos/bootstrap/bootstrap
Labels: cla-not-required

#7904 Reduce boilerplate in vic-machine API handlers
  lib/apiservers/service/restapi/configure_vic_machine.go
  lib/apiservers/service/restapi/handlers/client/client.go
  lib/apiservers/service/restapi/handlers/client/client_test.go
  lib/apiservers/service/restapi/handlers/common.go
  lib/apiservers/service/restapi/handlers/decode/references.go
  lib/apiservers/service/restapi/handlers/hello_get.go
  lib/apiservers/service/restapi/handlers/target/authentication.go
  lib/apiservers/service/restapi/handlers/target/target.go
  lib/apiservers/service/restapi/handlers/vch_cert_get.go
  lib/apiservers/service/restapi/handlers/vch_create.go
  lib/apiservers/service/restapi/handlers/vch_delete.go
  lib/apiservers/service/restapi/handlers/vch_get.go
  lib/apiservers/service/restapi/handlers/vch_list_get.go
  lib/apiservers/service/restapi/handlers/vch_log_get.go
  lib/apiservers/service/restapi/handlers/version_get.go
Labels: cla-not-required, team/lifecycle

#7544 vic-machine: Fix message from inspect config
  cmd/vic-machine/inspect/inspect.go
Labels: area/cli, cla-not-required, component/vic-machine, team/lifecycle

#7956 Add timeout variable for overflow servers
  .drone.yml
  tests/resources/VCH-Util.robot
Labels: cla-not-required

#7957 cherry pick: Do not accept DHCP DNS servers if manually defined. Check resolv.conf file for updated --dns-server instead of guestinfo. (#7824)
  lib/tether/ops_linux.go
  tests/test-cases/Group6-VIC-Machine/6-16-Config.robot
Labels: cla-not-required

#7963 cherry-pick: Allow for two different ping error messages (#7864)
  tests/test-cases/Group1-Docker-Commands/1-24-Docker-Link.robot
Labels: cla-not-required

#7960 vicadmin redirect/force TLS
  cmd/vicadmin/server.go
  tests/test-cases/Group9-VIC-Admin/9-01-VICAdmin-ShowHTML.robot
Labels: cla-not-required

#7966 Uncomment teardown in upgrade tests [specific ci=Group11-Upgrade]
  tests/test-cases/Group11-Upgrade/11-01-Upgrade.robot
Labels: cla-not-required

#7954 [skip ci] Remove vic-ui components
  .drone.yml
  .pullapprove.yml
  Makefile
  cmd/vic-ui/main.go
  cmd/vic-ui/ui/ui.go
  lib/install/plugin/register.go
  tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.md
  tests/manual-test-cases/Group18-VIC-UI/18-1-VIC-UI-Installer.robot
  tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.md
  tests/manual-test-cases/Group18-VIC-UI/18-2-VIC-UI-Uninstaller.robot
  tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-NGC-tests.md
  tests/manual-test-cases/Group18-VIC-UI/18-3-VIC-UI-NGC-tests.robot
  tests/manual-test-cases/Group18-VIC-UI/TestCases.md
  tests/manual-test-cases/Group18-VIC-UI/VicUiInstallPexpectLibrary.py
  tests/manual-test-cases/Group18-VIC-UI/setup-testbed.robot
  tests/manual-test-cases/Group18-VIC-UI/vicui-common.robot
  tests/manual-test-cases/TestGroups.md
Labels: cla-not-required

#7971 Fix VSAN testbed for 6.7 testing
  tests/nightly/jenkins-nightly-run.sh
  tests/resources/nimbus-testbeds/vic-vsan.rb
Labels: cla-not-required

#7961 Enable Group 23 - Vic Machine Service to run in parallel under CI
  tests/resources/Group23-VIC-Machine-Service-Util.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-01-Metadata.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-02-VCH-List.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-03-VCH-Create.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-04-VCH-Inspect.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-05-VCH-Logs.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-06-VCH-Certificate.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-08-VCH-Delete.robot
Labels: cla-not-required

#7977 Change encoding when attempting to cat syslog file
  tests/test-cases/Group6-VIC-Machine/6-15-Syslog.robot
Labels: cla-not-required

#7978 Provide per-suite vic-machine-server logs in CI
  tests/resources/Group23-VIC-Machine-Service-Util.robot
Labels: cla-not-required, team/lifecycle

#7979 Provide a VIC demo testbed for internal use in Nimbus
  tests/resources/nimbus-testbeds/vic-demo.rb
Labels: cla-not-required

#7967 Move code to size tempfs to iso building script
  isos/base/utils.sh
  isos/bootstrap.sh
  isos/bootstrap/bootstrap
Labels: cla-not-required

#7987 Improve docker cp test concurrency
  tests/test-cases/Group1-Docker-Commands/1-43-Docker-CP-Offline.robot
  tests/test-cases/Group1-Docker-Commands/1-44-Docker-CP-Online.robot
Labels: cla-not-required

#7992 cherry pick : Move affinity-vm-group flag from compute to create (#7786)
  cmd/vic-machine/common/compute.go
  cmd/vic-machine/create/create.go
Labels: cla-not-required

#7958 cherry pick: Support add and remove VM Group via configure (#7797)
  cmd/vic-machine/common/compute.go
  cmd/vic-machine/configure/configure.go
  cmd/vic-machine/create/create.go
  lib/install/data/data.go
  lib/install/management/configure.go
  lib/install/management/delete.go
  lib/install/management/vmgroup.go
  lib/install/validate/compute.go
  tests/resources/Group25-Host-Affinity-Util.robot
  tests/test-cases/Group25-Host-Affinity/25-01-Basic.md
  tests/test-cases/Group25-Host-Affinity/25-01-Basic.robot
  tests/test-cases/Group25-Host-Affinity/25-02-Reconfigure.md
  tests/test-cases/Group25-Host-Affinity/25-02-Reconfigure.robot
  tests/test-cases/Group25-Host-Affinity/TestCases.md
Labels: cla-not-required

#7988 Removed unnecessary kube API server address/port
  cmd/kubelet-starter/main.go
  cmd/vic-machine/common/kubelet.go
  cmd/vic-machine/create/create.go
  isos/bootstrap/bootstrap
  lib/install/management/appliance.go
  lib/install/validate/validator.go
Labels: cla-not-required

#8003 Add logging to nc test, otherwise it rarely gives any output
  tests/test-cases/Group6-VIC-Machine/6-07-Create-Network.robot
Labels: cla-not-required

#8005 Scope admin keywords so that they can be run in parallel
  tests/manual-test-cases/Group5-Functional-Tests/5-28-VICAdmin-Isolated.robot
  tests/resources/VCH-Util.robot
  tests/test-cases/Group9-VIC-Admin/9-01-VICAdmin-ShowHTML.robot
Labels: cla-not-required

#8010 Fix panic in listVCH if a VM is deleted in the middle
  pkg/vsphere/vm/vm.go
Labels: cla-not-required

#8002 Remove opsuser-specific affinity tests
  tests/test-cases/Group25-Host-Affinity/25-02-Reconfigure.md
  tests/test-cases/Group25-Host-Affinity/25-02-Reconfigure.robot
Labels: cla-not-required

#8014 Pin postgres image to avoid bad updates and fix a few network leaks
  tests/resources/dockerfiles/configs/depends_on/docker-compose.yml
  tests/test-cases/Group12-VCH-BC/12-01-Delete.robot
  tests/test-cases/Group23-VIC-Machine-Service/23-03-VCH-Create.robot
  tests/test-cases/Group25-Host-Affinity/25-01-Basic.robot
Labels: cla-not-required
